In [304]:
#무조건 조식 파일부터 실행해야함.
#안그러면 파일 수정이 안되서 오류남.

In [1]:

import win32com.client as win32
from contextlib import suppress
import shutil
from datetime import date, datetime, timedelta
import os
import re
from pathlib import Path
import pandas as pd
import numpy as np

#올해는 몇년도인가요?#########################################################(직접 작성)
now_y="25년"

origin_str = (datetime.now() - timedelta(weeks=2) - timedelta(days=1)).strftime("%m.%d")
#임시로 고정
origin_str = '2차서식'

#임시로 고정 ###########################################직접 수정
now_str = input("작업할 날짜를 넣어주세요")#"09.02"
print("작업할 파일의 날짜:",now_str)

# 이번달 
now_m = str(int(now_str[:2]))+"월"

source_folder = r".\{0}\{1}\{2}.{3}".format(now_y, now_m, str(int(now_str[:2])),str(int(now_str[3:])))  #메인경로 수정
print("가져올 폴더:",source_folder)

D:\Program_Files\anaconda3\envs\dx_env\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

작업할 날짜를 넣어주세요 12.31

작업할 파일의 날짜: 12.31
가져올 폴더: .\25년\12월\12.31

In [2]:
#작업할 요일에 따라 컬럼이 달라짐
today = input("요일을 넣어주세요")
col_name = {"월":"Unnamed: 5", "화":"Unnamed: 6", "수":"Unnamed: 7", "목":"Unnamed: 8", "금":"Unnamed: 9", "토":"Unnamed: 10", "일":"Unnamed: 11"}

요일을 넣어주세요 수

In [3]:
now_d=str(int(now_str[:2]))+"."+str(int(now_str[3:]))
now_d2 = now_d.replace(".","/")
print("서식변경한 오늘 날짜:",now_d2)

서식변경한 오늘 날짜: 12/31

In [21]:
#저속노화
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_저속노화.csv" #################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8')#'cp949' 'euc-kr' 'cp949'

#	45915'				
#					09/15 Mon 이런 형식으로 csv 파일 수정

df.loc[3:8,col_name[today]] #저속노화 
#df.loc[8:15,col_name[today]] #저당
#df.loc[17:22,col_name[today]] #고혈압

3          ★토마토두부면파스타
4           ★닭가슴살스테이크
5                채소피클
6                ★탄산수
7                 NaN
8    794kcal/98:33:30
Name: Unnamed: 7, dtype: object

In [22]:
# df.loc[11:16,col_name[today]] #저속노화 
#메인메뉴(저속노화, 저당, 고혈압)은 모두 메인메뉴 동일해서 main_menu0_1 하나로만 작업
main_menu0 = next((x for x in df.loc[3:7,col_name[today]] if (x.startswith("★"))&(type(x)==str)), None)
main_menu0_1 = main_menu0.replace("★","")
print(main_menu0_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
other_menu0_1 = [x.replace("★","") for x in df.loc[3:7, col_name[today]] if (x not in [main_menu0, main_menu0_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
print(other_menu0_1)
#칼로리정보
menu_data0_1 = df.loc[8,col_name[today]]
print(menu_data0_1)

# df.loc[18:23,col_name[today]] #저당 반찬
other_menu0_2 = [x.replace("★","") for x in df.loc[9:14, col_name[today]] if (x not in [main_menu0, main_menu0_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
print(other_menu0_2)
#칼로리정보
menu_data0_2 = df.loc[15,col_name[today]]
print(menu_data0_2)

# df.loc[25:30,col_name[today]] #고혈압 반찬
other_menu0_3 = [x.replace("★","") for x in df.loc[17:21, col_name[today]] if (x not in [main_menu0, main_menu0_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
print(other_menu0_3)
#칼로리정보
menu_data0_3 = df.loc[22,col_name[today]]
print(menu_data0_3)

토마토두부면파스타
['닭가슴살스테이크', '채소피클', '탄산수']
794kcal/98:33:30
['닭가슴살스테이크', '채소피클', '탄산수']
794kcal/98:33:30
['닭가슴살스테이크', '채소피클', '탄산수']
794kcal/98:33:30

In [32]:
#본관 중식

#주간식단 파일 위치 (매주 수동변경)
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_본관.csv" #####################파일 변경

df=pd.read_csv("./"+week_meal, encoding='utf-8')#'cp949' 'euc-kr' 'cp949'
display(df)

,123,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,NaN,NaN,NaN,NaN,692kcal/89:21:28,NaN,NaN,NaN,NaN,NaN
126,NaN,NaN,후 식,NaN,NaN,NaN,옥수수보리차,NaN,NaN,NaN,NaN,NaN
127,※ 원산지 : 끼니별 메뉴표에 별도 표기 *간편식 공산품은 제품 뒷면 표시사항 참고...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
#중식###########################################################################################################################
#본관 중식
df.loc[42:48,col_name[today]] #본관 화반(한식a) 중식
# df.loc[49:55,col_name[today]] #본관 우글지글(한식b) 중식
# df.loc[56:62,col_name[today]] #본관 백반한상 중식
# df.loc[63:69,col_name[today]] #본관 인터a(일미) 중식
# df.loc[70:76,col_name[today]] #본관 인터b(하오) 중식
# df.loc[77:80,col_name[today]] #본관 포메인 중식
# df.loc[81:81,col_name[today]] #추가배식대 #본관 후식(코너 did 맨아랫줄에 들어가는 것) 중식

# df.loc[83:86,col_name[today]] #본관 런치팩 중식
# df.loc[87:90,col_name[today]] #본관 샐러드팩 중식

# df.loc[91:93,col_name[today]] #본관 고피자팩 중식
# df.loc[94:96,col_name[today]] #본관 모스버거팩 중식
# df.loc[97:99,col_name[today]] #본관 자담치킨팩 중식

42            ★양지탕&양념다대기
43                 귀리기장밥
44             ★동그랑땡전&케첩
45                ★감자채볶음
46                ★콩나물무침
47               수제배추겉절이
48    1048kcal/154:36:32
Name: Unnamed: 7, dtype: object

In [34]:
#df.loc[42:48,col_name[today]] #본관 화반(한식a) 중식
#메인메뉴
main_menu1 = next((x for x in df.loc[42:47,col_name[today]] if x.startswith("★")), None)
main_menu1_1 = main_menu1.replace("★","")
#print(main_menu1_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
other_menu1 = [x.replace("★","") for x in df.loc[42:47, col_name[today]] if (x not in [main_menu1, main_menu1_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(other_menu1)
#칼로리정보
menu_data1 = df.loc[48,col_name[today]]
#print(menu_data1)

# df.loc[49:55,col_name[today]] #본관 우글지글(한식b) 중식
main_menu2 = next((x for x in df.loc[49:54,col_name[today]] if x.startswith("★")), None)
main_menu2_1 = main_menu2.replace("★","")
#print(main_menu2_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
other_menu2 = [x.replace("★","") for x in df.loc[49:54, col_name[today]] if (x not in [main_menu2, main_menu2_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"])]
#print(other_menu2)
#칼로리정보
menu_data2 = df.loc[55,col_name[today]]
#print(menu_data2)

# df.loc[56:62,col_name[today]] #본관 백반한상 중식
main_menu3 = next((x for x in df.loc[56:62,col_name[today]] if x.startswith("★")), None)
main_menu3_1 = main_menu3.replace("★","")
#print(main_menu3_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
other_menu3 = [x.replace("★","") for x in df.loc[56:61, col_name[today]] if (x not in [main_menu3, main_menu3_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(other_menu3)
#칼로리정보
menu_data3 = df.loc[62,col_name[today]]
#print(menu_data3)

# df.loc[63:69,col_name[today]] #본관 인터a(일미) 중식
main_menu4 = next((x for x in df.loc[63:68,col_name[today]] if x.startswith("★")), None)
main_menu4_1 = main_menu4.replace("★","")
#print(main_menu4_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
other_menu4 = [x.replace("★","") for x in df.loc[63:68, col_name[today]] if (x not in [main_menu4, main_menu4_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(other_menu4)
#칼로리정보
menu_data4 = df.loc[69,col_name[today]]
#print(menu_data4)

# df.loc[70:76,col_name[today]] #본관 인터b(하오) 중식
main_menu5 = next((x for x in df.loc[70:75,col_name[today]] if x.startswith("★")), None)
main_menu5_1 = main_menu5.replace("★","")
#print(main_menu5_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
other_menu5 = [x.replace("★","") for x in df.loc[70:75, col_name[today]] if (x not in [main_menu5, main_menu5_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(other_menu5)
#칼로리정보
menu_data5 = df.loc[76,col_name[today]]
#print(menu_data5)

# df.loc[77:80,col_name[today]] #본관 포메인 중식
main_menu6 = next((x for x in df.loc[77:79,col_name[today]] if x.startswith("★")), None)
main_menu6_1 = main_menu6.replace("★","")
#print(main_menu6_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
other_menu6 = [x.replace("★","") for x in df.loc[77:79, col_name[today]] if (x not in [main_menu6, main_menu6_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(other_menu6)
#칼로리정보
menu_data6 = df.loc[79,col_name[today]]
#print(menu_data6)

# df.loc[81:81,col_name[today]] #추가배식대 #본관 후식(코너 did 맨아랫줄에 들어가는 것) 중식 ###################################################
main_menu7 = next((x for x in df.loc[81:81,col_name[today]] if x.startswith("★")), None)
main_menu7_1=main_menu7.replace("★","")
#print(main_menu7_1)

# df.loc[83:86,col_name[today]] #본관 런치팩 중식
main_menu8 = next((x for x in df.loc[83:83,col_name[today]] if x.startswith("★")), None)
main_menu8_1=main_menu8.replace("★","")
#print(main_menu8_1)
#칼로리정보
menu_data8 = df.loc[86,col_name[today]]
#print(menu_data8)

# df.loc[87:90,col_name[today]] #본관 샐러드팩 중식
main_menu9 = next((x for x in df.loc[87:87,col_name[today]] if x.startswith("★")), None)
main_menu9_1=main_menu9.replace("★","")
#print(main_menu9_1)
#칼로리정보
menu_data9 = df.loc[90,col_name[today]]
#print(menu_data9)

# df.loc[91:93,col_name[today]] #본관 고피자팩 중식
main_menu10 = next((x for x in df.loc[91:91,col_name[today]] if x.startswith("★")), None)
main_menu10_1=main_menu10.replace("★","")
#print(main_menu10_1)
#칼로리정보
menu_data10 = df.loc[93,col_name[today]]
#print(menu_data10)

# df.loc[94:96,col_name[today]] #본관 모스버거팩 중식
main_menu11 = next((x for x in df.loc[94:94,col_name[today]] if x.startswith("★")), None)
main_menu11_1=main_menu11.replace("★","")
#print(main_menu11_1)
#칼로리정보
menu_data11 = df.loc[96,col_name[today]]
#print(menu_data11)

# df.loc[97:99,col_name[today]] #본관 자담치킨팩 중식
main_menu12 = next((x for x in df.loc[97:97,col_name[today]] if x.startswith("★")), None)
main_menu12_1=main_menu12.replace("★","")
#print(main_menu12_1)
#칼로리정보
menu_data22 = df.loc[99,col_name[today]]
#print(menu_data12)

In [40]:
#파워포인트 디렉토리
root_path=os.getcwd()
#print(root_path) #root 디렉토리
folder_path = root_path+"\\25년"+"\\"+now_m+"\\"+now_d+"\\" #폴더 디렉토리
print(folder_path)

#root파일명 
#메인 조식(건물명) 날짜 / 메인 중식(건물명) 날짜 / 메인 석식(건물명) 날짜 
#ex)메인 조식(본관) 8.25.pptx
file_name = "메인 중식" + "(본관) " + now_d + ".pptx"  #가운데 건물명 변경하면서 작업 
#print("확인용)",file_name)

#코너 파일명
#코너 조식 날짜 원산지 입력
#ex)코너 조식 8.25 원산지 입력
today_corner = f"메인 중식 {now_d} 원산지 입력.pptx"
print(today_corner)

D:\Program_Files\SNJ\현대그린푸드\25년\12월\12.31\
메인 중식 12.31 원산지 입력.pptx

In [41]:
#ppt 파일 열기
import win32com.client

file_name = f'메인 중식(본관) {now_d}.pptx'

#powerpoint = win32com.client.Dispatch('PowerPoint.Application') #읽기모드 (이러면 수정은 되지만 현재 파일에 덮어쓰는게 안됨)
#powerpoint.Visible = True #PPT창 보이게 하기 

#파워포인트 프레젠테이션 불러오기
powerpoint = win32.gencache.EnsureDispatch("PowerPoint.Application") #읽기쓰기 모드로 열어야 현재 파일에 덮어쓰기 가능
#기존 파일 불러오기 예시
#presentation = powerpoint.Presentations.Open(str(match[0].resolve(), WithWindow=False))###파일 열때 파일명 앞에 절대경로 수정 필요 

#본관 조식 작업
presentation = powerpoint.Presentations.Open(folder_path+file_name, ReadOnly=False, WithWindow=True) #WithWindow=False로 하면 화면 안열고 진행

In [42]:
#본관 중식 1번째 슬라이드
slide = presentation.Slides(1)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#런치
#메인메뉴 데이터 수정
shape_index = 21 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu8_1

#샐러드
#메인메뉴 데이터 수정
shape_index = 22 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu9_1

#버거
#메인메뉴 데이터 수정
shape_index = 24 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu11_1

#피자
#메인메뉴 데이터 수정
shape_index = 31 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu10_1

#치킨
#메인메뉴 데이터 수정
shape_index = 32 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu12_1

#저속노화
#메인메뉴 데이터 수정
shape_index = 26 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu0_1
# #반찬 수정
# shape_index = 30 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(other_menu0_1[:-1]) #저염김치 제외

In [43]:
#본관 중식 2번째 슬라이드
slide = presentation.Slides(2)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#백반한상
#메인메뉴 데이터 수정
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu3_1
#반찬 수정
# shape_index = 11 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(other_menu3)

#하오(인터b)
#메인메뉴 데이터 수정
shape_index = 13 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu5_1
# #반찬 수정
# shape_index = 16 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(other_menu5)

In [45]:
#본관 중식 3번째 슬라이드
slide = presentation.Slides(3)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#우글지글
#메인메뉴 데이터 수정
shape_index = 4 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu2_1
#반찬 수정
# shape_index = 5 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(other_menu2)

#일미(인터a)
#메인메뉴 데이터 수정
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu4_1
#반찬 수정
# shape_index = 15 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(other_menu4)

In [46]:
#본관 중식 4번째 슬라이드
slide = presentation.Slides(4)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#화반
#메인메뉴 데이터 수정
shape_index = 16 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu1_1
#반찬 수정
# shape_index = 18 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(other_menu1)

#포메인
#메인메뉴 데이터 수정
shape_index = 14 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu6_1.split("&")[0] #시그니쳐는 메인메뉴만 남김
#포메인은 설명과 영어를 같이 수작업 ###################################################################################

In [47]:
# 같은 파일에 덮어쓰기
presentation.Save()
# 닫기
presentation.Close()
#Quit는 Presentation(프레젠테이션) 객체가 아니라 Application(파워포인트 앱) 객체의 메서드라서 powerpoint를 닫아줘야함. 
#powerpoint.Quit()

In [48]:
#C지구###################################################################################################################

In [63]:
#주간식단 파일 위치 (매주 수동변경)
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_C.csv" #####################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8')#'cp949' 'euc-kr' 'cp949'
display(df)

,13,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,NaN,NaN,NaN,NaN,NaN,692kcal/89:21:28,NaN,NaN,NaN
116,NaN,NaN,후 식,NaN,NaN,NaN,옥수수보리차,NaN,NaN,NaN
117,※ 원산지 : 끼니별 메뉴표에 별도 표기 *간편식 공산품은 제품 뒷면 표시사항 참고...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [64]:
#C 중식
df.loc[42:48,col_name[today]] #C 화반(한식a) 중식
df.loc[49:55,col_name[today]] #C 우글지글(한식b) 중식
df.loc[56:62,col_name[today]] #C 인터a(일미) 중식
df.loc[63:69,col_name[today]] #C 인터b(하오) 중식
df.loc[70:73,col_name[today]] #C 모스버거 
df.loc[74:76,col_name[today]] #C 고피자 
df.loc[77:77,col_name[today]] #추가배식대 #C관 후식(코너 did 맨아랫줄에 들어가는 것) 중식
df.loc[79:82,col_name[today]] #C관 런치팩 중식
df.loc[83:86,col_name[today]] #C관 샐러드팩 중식
df.loc[87:89,col_name[today]] #C관 자담치킨팩 중식

87                      ★맵슐랭순살치킨
88    ★치킨무/소스2종/음료(Drink 中 택 1)
89             1038kcal/42:96:54
Name: Unnamed: 7, dtype: object

In [65]:
#df.loc[42:48,col_name[today]] #C 화반(한식a) 중식
#메인메뉴
c_main_menu1 = next((x for x in df.loc[42:47,col_name[today]] if x.startswith("★")), None)
c_main_menu1_1 = c_main_menu1.replace("★","")
#print(c_main_menu1_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
c_other_menu1 = [x.replace("★","") for x in df.loc[42:47, col_name[today]] if (x not in [c_main_menu1, c_main_menu1_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(c_other_menu1)
#칼로리정보
c_menu_data1 = df.loc[48,col_name[today]]
#print(c_menu_data1)

# df.loc[49:55,col_name[today]] #C 우글지글(한식b) 중식
#메인메뉴
c_main_menu2 = next((x for x in df.loc[49:54,col_name[today]] if x.startswith("★")), None)
c_main_menu2_1 = c_main_menu2.replace("★","")
#print(c_main_menu2_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
c_other_menu2 = [x.replace("★","") for x in df.loc[49:54, col_name[today]] if (x not in [c_main_menu2, c_main_menu2_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(c_other_menu2)
#칼로리정보
c_menu_data2 = df.loc[55,col_name[today]]
#print(c_menu_data2)

# df.loc[56:62,col_name[today]] #C 인터a(일미) 중식
#메인메뉴
c_main_menu3 = next((x for x in df.loc[56:61,col_name[today]] if x.startswith("★")), None)
c_main_menu3_1 = c_main_menu3.replace("★","")
#print(c_main_menu3_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
c_other_menu3 = [x.replace("★","") for x in df.loc[56:61, col_name[today]] if (x not in [c_main_menu3, c_main_menu3_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(c_other_menu3)
#칼로리정보
c_menu_data3 = df.loc[62,col_name[today]]
#print(c_menu_data3)

# df.loc[63:69,col_name[today]] #C 인터b(하오) 중식
#메인메뉴
c_main_menu4 = next((x for x in df.loc[63:68,col_name[today]] if x.startswith("★")), None)
c_main_menu4_1 = c_main_menu4.replace("★","")
#print(c_main_menu4_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
c_other_menu4 = [x.replace("★","") for x in df.loc[63:68, col_name[today]] if (x not in [c_main_menu4, c_main_menu4_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(c_other_menu4)
#칼로리정보
c_menu_data4 = df.loc[69,col_name[today]]
#print(c_menu_data4)

# df.loc[70:73,col_name[today]] #C 모스버거 
c_main_menu5 = next((x for x in df.loc[70:72,col_name[today]] if x.startswith("★")), None)
c_main_menu5_1=c_main_menu5.replace("★","")
#print(c_main_menu5_1)
#칼로리정보
c_menu_data5 = df.loc[73,col_name[today]]
#print(c_menu_data5)

# df.loc[74:76,col_name[today]] #C 고피자 
c_main_menu6 = next((x for x in df.loc[74:75,col_name[today]] if x.startswith("★")), None)
c_main_menu6_1=c_main_menu6.replace("★","")
#print(c_main_menu6_1)
#칼로리정보
c_menu_data6 = df.loc[76,col_name[today]]
#print(c_menu_data6)

# df.loc[77:77,col_name[today]] #추가배식대 #C관 후식(코너 did 맨아랫줄에 들어가는 것) 중식
c_main_menu7 = next((x for x in df.loc[77:77,col_name[today]] if x.startswith("★")), None)
c_main_menu7_1=c_main_menu7.replace("★","")
#print(c_main_menu7_1)

# df.loc[79:82,col_name[today]] #C관 런치팩 중식
c_main_menu8 = next((x for x in df.loc[79:81,col_name[today]] if x.startswith("★")), None)
c_main_menu8_1=c_main_menu8.replace("★","")
#print(c_main_menu8_1)
#칼로리정보
c_menu_data8 = df.loc[82,col_name[today]]
#print(c_menu_data8)

# df.loc[83:85,col_name[today]] #C관 샐러드팩 중식
c_main_menu9 = next((x for x in df.loc[83:85,col_name[today]] if x.startswith("★")), None)
c_main_menu9_1=c_main_menu9.replace("★","")
#print(c_main_menu9_1)
#칼로리정보
c_menu_data9 = df.loc[86,col_name[today]]
#print(c_menu_data9)

# df.loc[86:89,col_name[today]] #C관 자담치킨팩 중식
c_main_menu10 = next((x for x in df.loc[87:89,col_name[today]] if x.startswith("★")), None)
c_main_menu10_1=c_main_menu10.replace("★","")
#print(c_main_menu10_1)
#칼로리정보
c_menu_data10 = df.loc[89,col_name[today]]
#print(c_menu_data10)

In [66]:
#ppt 파일 열기
import win32com.client

file_name = f'메인 중식(C지구) {now_d}.pptx'

#powerpoint = win32com.client.Dispatch('PowerPoint.Application') #읽기모드 (이러면 수정은 되지만 현재 파일에 덮어쓰는게 안됨)
#powerpoint.Visible = True #PPT창 보이게 하기 

#파워포인트 프레젠테이션 불러오기
powerpoint = win32.gencache.EnsureDispatch("PowerPoint.Application") #읽기쓰기 모드로 열어야 현재 파일에 덮어쓰기 가능
#기존 파일 불러오기 예시
#presentation = powerpoint.Presntations.Open(str(match[0].resolve(), WithWindow=False))###파일 열때 파일명 앞에 절대경로 수정 필요 

#본관 조식 작업
presentation = powerpoint.Presentations.Open(folder_path+file_name, ReadOnly=False, WithWindow=True) #WithWindow=False로 하면 화면 안열고 진행

In [67]:
#C 중식 1번째 슬라이드
slide = presentation.Slides(1)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#우글지글
#메인메뉴 데이터 수정
shape_index = 26 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu3_1
# #반찬 수정
# shape_index = 28 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(c_other_menu3)

In [68]:
#C 중식 2번째 슬라이드
slide = presentation.Slides(2)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#런치팩
#메인메뉴 데이터 수정
shape_index = 28 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu8_1

#샐러드팩
#메인메뉴 데이터 수정
shape_index = 29 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu9_1

#외식브랜드팩(치킨만)
#메인메뉴 데이터 수정
shape_index = 20 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu10_1

#하오(인터b)
#메인메뉴 데이터 수정
shape_index = 23 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu4_1
#반찬 수정
# shape_index = 26 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(c_other_menu3)

In [69]:
#C 중식 3번째 슬라이드
slide = presentation.Slides(3)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 16 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu2_1
#반찬 수정
# shape_index = 17 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(c_other_menu2)

#고피자
#메인메뉴 데이터 수정
shape_index = 13 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu6_1

In [70]:
#C 중식 4번째 슬라이드
slide = presentation.Slides(4)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#화반(한식a)
#메인메뉴 데이터 수정
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu1_1
#반찬 수정
# shape_index = 13 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(c_other_menu1)

#모스버거
#메인메뉴 데이터 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu5_1

In [71]:
# 같은 파일에 덮어쓰기
presentation.Save()
# 닫기
presentation.Close()
#Quit는 Presentation(프레젠테이션) 객체가 아니라 Application(파워포인트 앱) 객체의 메서드라서 powerpoint를 닫아줘야함. 
#powerpoint.Quit()

In [72]:
#C1#########################################################################################################################

In [75]:
#주간식단 파일 위치 (매주 수동변경)
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_C1.csv" #####################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8') #'cp949' 'euc-kr' 'cp949'
display(df)

,13,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
76,NaN,NaN,NaN,NaN,NaN,NaN,★궁채장아찌,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,깍두기,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,1025kcal/152:30:33,NaN,NaN,NaN
79,NaN,NaN,후 식,NaN,NaN,NaN,옥수수보리차,NaN,NaN,NaN
80,※ 원산지 : 끼니별 메뉴표에 별도 표기 *간편식 공산품은 제품 뒷면 표시사항 참고...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
print(df.loc[21:27,col_name[today]]) #C1 화반(한식a) 중식
print(df.loc[28:34,col_name[today]]) #C1 우글지글(한식b) 중식
print(df.loc[35:41,col_name[today]]) #C1 인터 중식
print(df.loc[42:46,col_name[today]]) #C1 더팬 중식
print(df.loc[47:50,col_name[today]]) #C1 자담치킨 중식
print(df.loc[51:51,col_name[today]]) #추가배식대 #C1관 후식(코너 did 맨아랫줄에 들어가는 것) 중식

print(df.loc[53:56,col_name[today]]) #C1 런치팩
print(df.loc[57:60,col_name[today]]) #C1 샐러드팩 
print(df.loc[61:63,col_name[today]]) #C1관 고피자팩 중식
print(df.loc[64:66,col_name[today]]) #C1관 프랭크 버거팩 중식

21            ★양지탕&양념다대기
22                 귀리기장밥
23             ★동그랑땡전&케첩
24                ★감자채볶음
25                ★콩나물무침
26               수제배추겉절이
27    1048kcal/154:36:32
Name: Unnamed: 7, dtype: object
28            ★양지탕&양념다대기
29                 귀리기장밥
30             ★동그랑땡전&케첩
31                ★감자채볶음
32                ★콩나물무침
33               수제배추겉절이
34    1048kcal/154:36:32
Name: Unnamed: 7, dtype: object
35               ★경양식돈까스
36                  흑임자밥
37              ★파슬리크림수프
38                 ★채소쫄면
39                  오이피클
40                   깍두기
41    1065kcal/156:36:33
Name: Unnamed: 7, dtype: object
42              ★불고기반미버거
43                 ★크림수프
44            ★오이피클&할라피뇨
45                   깍두기
46    1033kcal/154:30:33
Name: Unnamed: 7, dtype: object
47             ★맵슐랭순살치킨
48                 ★치킨무
49     ★탄산음료(콜라,사이다 택1)
50    1038kcal/42:96:54
Name: Unnamed: 7, dtype: object
51    ★그린샐러드&드레싱2종&콘샐러드
Name: Unnamed: 7, dtype: object
53     ★불닭샌드위치&오지치즈후라이
54         ★Side 中 택 1
55        ★Drink 中 택 1
56    554kcal/51:28:26
Name: Unnamed: 7, dtype: object
57      ★포크케밥샐러드&모둠과일&단호박범벅
58              ★Side 中 택 1
59             ★Drink 中 택 1
60         458kcal/39:35:16
Name: Unnamed: 7, dtype: object
61                    ★k-불고기 피자
62    ★소스2종/피클/음료(Drink 中 택 1)
63            1125kcal/68:94:53
Name: Unnamed: 7, dtype: object
64                      ★쉬림프버거
65    ★감자튀김&케첩/음료(Drink 中 택 1)
66            568Kcal/77:10:14
Name: Unnamed: 7, dtype: object

In [77]:
# df.loc[21:27,col_name[today]] #C1 화반(한식a) 중식
#메인메뉴
c1_main_menu1 = next((x for x in df.loc[21:26,col_name[today]] if x.startswith("★")), None)
c1_main_menu1_1 = c1_main_menu1.replace("★","")
#print(c1_main_menu1_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
c1_other_menu1 = [x.replace("★","") for x in df.loc[21:26, col_name[today]] if (x not in [c1_main_menu1, c1_main_menu1_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(c1_other_menu1)
#칼로리정보
c1_menu_data1 = df.loc[27,col_name[today]]
#print(c1_menu_data1)

# df.loc[28:34,col_name[today]] #C1 우글지글(한식b) 중식
#메인메뉴
c1_main_menu2 = next((x for x in df.loc[28:33,col_name[today]] if x.startswith("★")), None)
c1_main_menu2_1 = c1_main_menu2.replace("★","")
#print(c1_main_menu2_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
c1_other_menu2 = [x.replace("★","") for x in df.loc[28:33, col_name[today]] if (x not in [c1_main_menu2, c1_main_menu2_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(c1_other_menu2)
#칼로리정보
c1_menu_data2 = df.loc[34,col_name[today]]
#print(c1_menu_data2)

# df.loc[35:41,col_name[today]] #C1 인터 중식
#메인메뉴
c1_main_menu3 = next((x for x in df.loc[35:40,col_name[today]] if x.startswith("★")), None)
c1_main_menu3_1 = c1_main_menu3.replace("★","")
#print(c1_main_menu3_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
c1_other_menu3 = [x.replace("★","") for x in df.loc[35:40, col_name[today]] if (x not in [c1_main_menu3, c1_main_menu3_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(c1_other_menu3)
#칼로리정보
c1_menu_data3 = df.loc[41,col_name[today]]
#print(c1_menu_data3)

# df.loc[42:46,col_name[today]] #C1 더팬 중식
#메인메뉴
c1_main_menu4 = next((x for x in df.loc[42:45,col_name[today]] if x.startswith("★")), None)
c1_main_menu4_1 = c1_main_menu4.replace("★","")
#print(c1_main_menu4_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
c1_other_menu4 = [x.replace("★","") for x in df.loc[42:45, col_name[today]] if (x not in [c1_main_menu4, c1_main_menu4_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(c1_other_menu4)
#칼로리정보
c1_menu_data4 = df.loc[46,col_name[today]]
#print(c1_menu_data4)

# df.loc[47:50,col_name[today]] #C1 자담치킨 중식
#메인메뉴
c1_main_menu5 = next((x for x in df.loc[47:49,col_name[today]] if x.startswith("★")), None)
c1_main_menu5_1 = c1_main_menu5.replace("★","")
#print(c1_main_menu5_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
c1_other_menu5 = [x.replace("★","") for x in df.loc[47:49, col_name[today]] if (x not in [c1_main_menu5, c1_main_menu5_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
#print(c1_other_menu5)
#칼로리정보
c1_menu_data5 = df.loc[50,col_name[today]]
#print(c1_menu_data5)

# df.loc[51:51,col_name[today]] #추가배식대 #C1관 후식(코너 did 맨아랫줄에 들어가는 것) 중식
c1_main_menu6 = next((x for x in df.loc[51:51,col_name[today]] if x.startswith("★")), None)
c1_main_menu6_1 = c1_main_menu6.replace("★","")
#print(c1_main_menu6_1)

# df.loc[53:56,col_name[today]] #C1 런치팩
c1_main_menu7 = next((x for x in df.loc[53:55,col_name[today]] if x.startswith("★")), None)
c1_main_menu7_1 = c1_main_menu7.replace("★","")
#print(c1_main_menu7_1)
#칼로리정보
c1_menu_data7 = df.loc[56,col_name[today]]
#print(c1_menu_data7)

# df.loc[57:60,col_name[today]] #C1 샐러드팩 
c1_main_menu8 = next((x for x in df.loc[57:59,col_name[today]] if x.startswith("★")), None)
c1_main_menu8_1 = c1_main_menu8.replace("★","")
#print(c1_main_menu8_1)
#칼로리정보
c1_menu_data8 = df.loc[60,col_name[today]]
#print(c1_menu_data8)

# df.loc[61:63,col_name[today]] #C1관 고피자팩 중식
c1_main_menu9 = next((x for x in df.loc[61:62,col_name[today]] if x.startswith("★")), None)
c1_main_menu9_1 = c1_main_menu9.replace("★","")
#print(c1_main_menu9_1)
#칼로리정보
c1_menu_data9 = df.loc[63,col_name[today]]
#print(c1_menu_data9)

# df.loc[64:66,col_name[today]] #C1관 모스버거팩 중식
c1_main_menu10 = next((x for x in df.loc[64:65,col_name[today]] if x.startswith("★")), None)
c1_main_menu10_1 = c1_main_menu10.replace("★","")
print(c1_main_menu10_1)
#칼로리정보
c1_menu_data10 = df.loc[66,col_name[today]]
print(c1_menu_data10)

쉬림프버거
568Kcal/77:10:14

In [78]:
#ppt 파일 열기
import win32com.client

file_name = f'메인 중식(씨원) {now_d}.pptx'

#powerpoint = win32com.client.Dispatch('PowerPoint.Application') #읽기모드 (이러면 수정은 되지만 현재 파일에 덮어쓰는게 안됨)
#powerpoint.Visible = True #PPT창 보이게 하기 

#파워포인트 프레젠테이션 불러오기
powerpoint = win32.gencache.EnsureDispatch("PowerPoint.Application") #읽기쓰기 모드로 열어야 현재 파일에 덮어쓰기 가능
#기존 파일 불러오기 예시
#presentation = powerpoint.Presentations.Open(str(match[0].resolve(), WithWindow=False))###파일 열때 파일명 앞에 절대경로 수정 필요 

#본관 조식 작업
presentation = powerpoint.Presentations.Open(folder_path+file_name, ReadOnly=False, WithWindow=True) #WithWindow=False로 하면 화면 안열고 진행

In [79]:
#C1 중식 1번째 슬라이드
slide = presentation.Slides(1)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#df.loc[21:27,col_name[today]] #C1 화반(한식a) 중식
#화반(한식a)
#메인메뉴 데이터 수정
shape_index = 12 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu1_1
#반찬 수정
# shape_index = 12 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(c1_other_menu1)

# df.loc[35:41,col_name[today]] #C1 인터 중식
#메인메뉴 데이터 수정
shape_index = 14 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu3_1
#반찬 수정
# shape_index = 17 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(c1_other_menu3)

In [80]:
#C1 중식 2번째 슬라이드
slide = presentation.Slides(2)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

# df.loc[47:50,col_name[today]] #C1 자담치킨 중식
#메인메뉴 데이터 수정
shape_index = 22 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu5_1

# df.loc[53:56,col_name[today]] #C1 런치팩
shape_index = 28 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu7_1

# df.loc[57:60,col_name[today]] #C1 샐러드팩 
shape_index = 29 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu8_1

# df.loc[61:63,col_name[today]] #C1관 고피자팩 중식
shape_index = 32 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu9_1

# df.loc[64:66,col_name[today]] #C1관 모스버거팩 중식
shape_index = 31 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu10_1

In [81]:
#C1 중식 3번째 슬라이드
slide = presentation.Slides(3)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

# df.loc[28:34,col_name[today]] #C1 우글지글(한식b) 중식
#메인메뉴 데이터 수정
shape_index = 12 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu2_1
#반찬 수정
# shape_index = 12 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(c1_other_menu2)

# df.loc[42:46,col_name[today]] #C1 더팬 중식
#메인메뉴 데이터 수정
shape_index = 14 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu4_1
#반찬 수정
# shape_index = 17 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(c1_other_menu4)

In [82]:
# 같은 파일에 덮어쓰기
presentation.Save()
# 닫기
presentation.Close()
#Quit는 Presentation(프레젠테이션) 객체가 아니라 Application(파워포인트 앱) 객체의 메서드라서 powerpoint를 닫아줘야함. 
#powerpoint.Quit()

In [83]:
#A1#########################################################################################################################

In [84]:
#주간식단 파일 위치 (매주 수동변경)
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_A1.csv" #####################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8') #'cp949' 'euc-kr' 'cp949'
#display(df)

In [85]:
df.loc[21:27,col_name[today]] #a1 고슬고슬 중식
df.loc[28:34,col_name[today]] #a1 한식 중식
df.loc[35:41,col_name[today]] #a1 인터 중식
df.loc[42:42,col_name[today]] #추가배식대 #a1관 후식(코너 did 맨아랫줄에 들어가는 것) 중식

df.loc[44:47,col_name[today]] #a1 런치팩
df.loc[48:51,col_name[today]] #a1 샐러드팩 
df.loc[52:54,col_name[today]] #a1관 고피자팩 중식
df.loc[55:57,col_name[today]] #a1관 모스버거팩 중식
df.loc[58:60,col_name[today]] #a1관 자담치킨팩 중식

58                      ★맵슐랭순살치킨
59    ★치킨무/소스2종/음료(Drink 中 택 1)
60             1038kcal/42:96:54
Name: Unnamed: 7, dtype: object

In [86]:
# df.loc[21:27,col_name[today]] #고슬고슬 a1 중식
#메인메뉴
a1_main_menu1 = next((x for x in df.loc[21:26,col_name[today]] if x.startswith("★")), None)
a1_main_menu1_1 = a1_main_menu1.replace("★","")
print(a1_main_menu1_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
a1_other_menu1 = [x.replace("★","") for x in df.loc[21:26, col_name[today]] if (x not in [a1_main_menu1, a1_main_menu1_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
print(a1_other_menu1)
#칼로리정보
a1_menu_data1 = df.loc[27,col_name[today]]
print(a1_menu_data1)

# df.loc[28:34,col_name[today]] #a1 한식 중식
#메인메뉴
a1_main_menu2 = next((x for x in df.loc[28:33,col_name[today]] if x.startswith("★")), None)
a1_main_menu2_1 = a1_main_menu2.replace("★","")
print(a1_main_menu2_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
a1_other_menu2 = [x.replace("★","") for x in df.loc[28:33, col_name[today]] if (x not in [a1_main_menu2, a1_main_menu2_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
print(a1_other_menu2)
#칼로리정보
a1_menu_data2 = df.loc[34,col_name[today]]
print(a1_menu_data2)

# df.loc[35:41,col_name[today]] #a1 인터 중식
#메인메뉴
a1_main_menu3 = next((x for x in df.loc[35:40,col_name[today]] if x.startswith("★")), None)
a1_main_menu3_1 = a1_main_menu3.replace("★","")
print(a1_main_menu3_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
a1_other_menu3 = [x.replace("★","") for x in df.loc[35:40, col_name[today]] if (x not in [a1_main_menu3, a1_main_menu3_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
print(a1_other_menu3)
#칼로리정보
a1_menu_data3 = df.loc[41,col_name[today]]
print(a1_menu_data3)

# df.loc[42:42,col_name[today]] #추가배식대 #C1관 후식(코너 did 맨아랫줄에 들어가는 것) 중식
a1_main_menu4 = next((x for x in df.loc[42:42,col_name[today]] if x.startswith("★")), None)
a1_main_menu4_1 = a1_main_menu4.replace("★","")
print(a1_main_menu4_1)

#df.loc[44:47,col_name[today]] #a1 런치팩
a1_main_menu5 = next((x for x in df.loc[44:46,col_name[today]] if x.startswith("★")), None)
a1_main_menu5_1 = a1_main_menu5.replace("★","")
print(a1_main_menu5_1)
#칼로리정보
a1_menu_data5 = df.loc[47,col_name[today]]
print(a1_menu_data5)

#df.loc[48:51,col_name[today]] #a1 샐러드팩 
a1_main_menu6 = next((x for x in df.loc[48:50,col_name[today]] if x.startswith("★")), None)
a1_main_menu6_1 = a1_main_menu6.replace("★","")
print(a1_main_menu6_1)
#칼로리정보
a1_menu_data6 = df.loc[51,col_name[today]]
print(a1_menu_data6)


#df.loc[52:54,col_name[today]] #a1관 고피자팩 중식
a1_main_menu7 = next((x for x in df.loc[52:53,col_name[today]] if x.startswith("★")), None)
a1_main_menu7_1 = a1_main_menu7.replace("★","")
print(a1_main_menu7_1)
#칼로리정보
a1_menu_data7 = df.loc[54,col_name[today]]
print(a1_menu_data7)

#df.loc[55:57,col_name[today]] #a1관 모스버거팩 중식
a1_main_menu8 = next((x for x in df.loc[55:56,col_name[today]] if x.startswith("★")), None)
a1_main_menu8_1 = a1_main_menu8.replace("★","")
print(a1_main_menu8_1)
#칼로리정보
a1_menu_data8 = df.loc[57,col_name[today]]
print(a1_menu_data8)

#df.loc[58:60,col_name[today]] #a1관 자담치킨팩 중식
a1_main_menu9 = next((x for x in df.loc[58:59,col_name[today]] if x.startswith("★")), None)
a1_main_menu9_1 = a1_main_menu9.replace("★","")
print(a1_main_menu9_1)
#칼로리정보
a1_menu_data9 = df.loc[60,col_name[today]]
print(a1_menu_data9)

미운영
[]
nan
미운영
[]
nan
경양식돈까스
['흑임자밥', '파슬리크림수프', '채소쫄면', '오이피클']
1065kcal/156:36:33
그린샐러드&드레싱2종&콘샐러드
불닭샌드위치&오지치즈후라이
554kcal/51:28:26
Side 中 택 1
458kcal/39:35:16
k-불고기 피자
1125kcal/68:94:53
쉬림프버거
568Kcal/77:10:14
맵슐랭순살치킨
1038kcal/42:96:54

In [87]:
#ppt 파일 열기
import win32com.client

file_name = f'메인 중식(디자인) {now_d}.pptx'

#powerpoint = win32com.client.Dispatch('PowerPoint.Application') #읽기모드 (이러면 수정은 되지만 현재 파일에 덮어쓰는게 안됨)
#powerpoint.Visible = True #PPT창 보이게 하기 

#파워포인트 프레젠테이션 불러오기
powerpoint = win32.gencache.EnsureDispatch("PowerPoint.Application") #읽기쓰기 모드로 열어야 현재 파일에 덮어쓰기 가능
#기존 파일 불러오기 예시
#presentation = powerpoint.Presentations.Open(str(match[0].resolve(), WithWindow=False))###파일 열때 파일명 앞에 절대경로 수정 필요 

#본관 조식 작업
presentation = powerpoint.Presentations.Open(folder_path+file_name, ReadOnly=False, WithWindow=True) #WithWindow=False로 하면 화면 안열고 진행

In [88]:
#a1 중식 1번째 슬라이드
slide = presentation.Slides(1)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#df.loc[21:27,col_name[today]] #a1 화반(한식a) 중식
#화반(한식a)
#메인메뉴 데이터 수정
shape_index = 12 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu1_1
#반찬 수정
# shape_index = 12 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(a1_other_menu1)

In [89]:
#a1 중식 2번째 슬라이드
slide = presentation.Slides(2)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

# df.loc[53:56,col_name[today]] #a1 런치팩
shape_index = 28 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu5_1

# df.loc[57:60,col_name[today]] #a1 샐러드팩 
shape_index = 29 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu6_1

# df.loc[64:66,col_name[today]] #a1관 모스버거팩 중식
shape_index = 31 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu8_1

# df.loc[61:63,col_name[today]] #C1관 고피자팩 중식
shape_index = 32 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu7_1

# df.loc[47:50,col_name[today]] #C1 자담치킨 중식
#메인메뉴 데이터 수정
shape_index = 33 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu9_1

In [90]:
#a1 중식 3번째 슬라이드
slide = presentation.Slides(3)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#df.loc[28:34,col_name[today]] #a1 한식 중식
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu2_1
#반찬 수정
# shape_index = 11 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(a1_other_menu2)

#df.loc[35:41,col_name[today]] #a1 인터 중식#메인메뉴 데이터 수정
shape_index = 13 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu3_1
#반찬 수정
# shape_index = 16 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(a1_other_menu3)

In [91]:
# 같은 파일에 덮어쓰기
presentation.Save()
# 닫기
presentation.Close()
#Quit는 Presentation(프레젠테이션) 객체가 아니라 Application(파워포인트 앱) 객체의 메서드라서 powerpoint를 닫아줘야함. 
#powerpoint.Quit()

In [92]:
#A2#########################################################################################################################

In [93]:
#주간식단 파일 위치 (매주 수동변경)
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_A2.csv" #####################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8') #'cp949' 'euc-kr' 'cp949'
display(df)

,13,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
78,NaN,NaN,NaN,NaN,NaN,NaN,★궁채장아찌,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,깍두기,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,1025kcal/152:30:33,NaN,NaN,NaN
81,NaN,NaN,후 식,NaN,NaN,NaN,옥수수보리차,NaN,NaN,NaN
82,※ 원산지 : 끼니별 메뉴표에 별도 표기 *간편식 공산품은 제품 뒷면 표시사항 참고...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [94]:
#파워트레인
#df.loc[21:27,col_name[today]] #a2 고슬고슬 중식
df.loc[29:35,col_name[today]] #a2 고슬고슬 중식

# df.loc[28:34,col_name[today]] #a2 한식 중식
df.loc[36:42,col_name[today]] #a2 한식 중식

# df.loc[35:41,col_name[today]] #a2 인터 중식
df.loc[43:49,col_name[today]] #a2 인터 중식

# df.loc[42:42,col_name[today]] #추가배식대 #a2관 후식(코너 did 맨아랫줄에 들어가는 것) 중식
df.loc[50:50,col_name[today]] #추가배식대 #a2관 후식(코너 did 맨아랫줄에 들어가는 것) 중식

# df.loc[44:47,col_name[today]] #a2 런치팩
df.loc[52:55,col_name[today]] #a2 런치팩

# df.loc[48:51,col_name[today]] #a2 샐러드팩 
df.loc[56:59,col_name[today]] #a2 샐러드팩

# df.loc[52:54,col_name[today]] #a2관 고피자팩 중식
df.loc[60:62,col_name[today]] #a2관 고피자팩 중식

# df.loc[55:57,col_name[today]] #a2관 모스버거팩 중식
df.loc[63:65,col_name[today]] #a2관 모스버거팩 중식

# df.loc[58:60,col_name[today]] #a2관 자담치킨팩 중식
df.loc[66:68,col_name[today]] #a2관 자담치킨팩 중식

66                      ★맵슐랭순살치킨
67    ★치킨무/소스2종/음료(Drink 中 택 1)
68             1038kcal/42:96:54
Name: Unnamed: 7, dtype: object

In [95]:
# df.loc[21:27,col_name[today]] #a2 고슬고슬 중식
#메인메뉴
a2_main_menu1 = next((x for x in df.loc[29:34,col_name[today]] if x.startswith("★")), None)
a2_main_menu1_1 = a2_main_menu1.replace("★","")
print(a2_main_menu1_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
a2_other_menu1 = [x.replace("★","") for x in df.loc[29:34, col_name[today]] if (x not in [a2_main_menu1, a2_main_menu1_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
print(a2_other_menu1)
#칼로리정보
a2_menu_data1 = df.loc[35,col_name[today]]
print(a2_menu_data1)

# df.loc[28:34,col_name[today]] #a2 한식 중식
#메인메뉴
a2_main_menu2 = next((x for x in df.loc[36:41,col_name[today]] if x.startswith("★")), None)
a2_main_menu2_1 = a2_main_menu2.replace("★","")
print(a2_main_menu2_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
a2_other_menu2 = [x.replace("★","") for x in df.loc[36:41, col_name[today]] if (x not in [a2_main_menu2, a2_main_menu2_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
print(a2_other_menu2)
#칼로리정보
a2_menu_data2 = df.loc[42,col_name[today]]
print(a2_menu_data2)

# df.loc[35:41,col_name[today]] #a2 인터 중식
#메인메뉴
a2_main_menu3 = next((x for x in df.loc[43:48,col_name[today]] if x.startswith("★")), None)
a2_main_menu3_1 = a2_main_menu3.replace("★","")
print(a2_main_menu3_1)
#그외 메뉴들 (메인에 들어가면 안되는 반찬 제외)
#공백은 float이라서 문자열을 처리하는데 오류가 생김 따라서 str형 데이터만 처리할 수 있도록 조건 추가 
a2_other_menu3 = [x.replace("★","") for x in df.loc[43:48, col_name[today]] if (x not in [a2_main_menu3, a2_main_menu3_1, "깍두기", "누룽지숭늉", "배추김치", "수제배추겉절이", "포기김치"]) & (type(x)==str)]
print(a2_other_menu3)
#칼로리정보
a2_menu_data3 = df.loc[49,col_name[today]]
print(a2_menu_data3)

# df.loc[42:42,col_name[today]] #추가배식대 #a2관 후식(코너 did 맨아랫줄에 들어가는 것) 중식
a2_main_menu4 = next((x for x in df.loc[50:50,col_name[today]] if x.startswith("★")), None)
a2_main_menu4_1 = a2_main_menu4.replace("★","")
print(a2_main_menu4_1)

#df.loc[52:55,col_name[today]] #a2 런치팩
a2_main_menu5 = next((x for x in df.loc[52:54,col_name[today]] if x.startswith("★")), None)
a2_main_menu5_1 = a2_main_menu5.replace("★","")
print(a2_main_menu5_1)
#칼로리정보
a2_menu_data5 = df.loc[55,col_name[today]]
print(a2_menu_data5)

#df.loc[56:59,col_name[today]] #a2 샐러드팩  
a2_main_menu6 = next((x for x in df.loc[56:58,col_name[today]] if x.startswith("★")), None)
a2_main_menu6_1 = a2_main_menu6.replace("★","")
print(a2_main_menu6_1)
#칼로리정보
a2_menu_data6 = df.loc[59,col_name[today]]
print(a2_menu_data6)

#df.loc[60:62,col_name[today]] #a2관 고피자팩 중식
a2_main_menu7 = next((x for x in df.loc[60:61,col_name[today]] if x.startswith("★")), None)
a2_main_menu7_1 = a2_main_menu7.replace("★","")
print(a2_main_menu7_1)
#칼로리정보
a2_menu_data7 = df.loc[62,col_name[today]]
print(a2_menu_data7)

#df.loc[63:65,col_name[today]] #a2관 모스버거팩 중식
a2_main_menu8 = next((x for x in df.loc[63:64,col_name[today]] if x.startswith("★")), None)
a2_main_menu8_1 = a2_main_menu8.replace("★","")
print(a2_main_menu8_1)
#칼로리정보
a2_menu_data8 = df.loc[65,col_name[today]]
print(a2_menu_data8)

#df.loc[66:68,col_name[today]] #a2관 자담치킨팩 중식
a2_main_menu9 = next((x for x in df.loc[66:67,col_name[today]] if x.startswith("★")), None)
a2_main_menu9_1 = a2_main_menu9.replace("★","")
print(a2_main_menu9_1)
#칼로리정보
a2_menu_data9 = df.loc[68,col_name[today]]
print(a2_menu_data9)

직화콩나물불고기
['귀리기장솥밥', '미역국', '깻잎무쌈', '둥굴레차']
1057kcal/154:36:33
양지탕&양념다대기
['귀리기장밥', '동그랑땡전&케첩', '감자채볶음', '콩나물무침']
1048kcal/154:36:32
경양식돈까스
['흑임자밥', '파슬리크림수프', '채소쫄면', '오이피클']
1065kcal/156:36:33
그린샐러드&드레싱2종&콘샐러드
불닭샌드위치&오지치즈후라이
554kcal/51:28:26
Side 中 택 1
458kcal/39:35:16
k-불고기 피자
1125kcal/68:94:53
쉬림프버거
568Kcal/77:10:14
맵슐랭순살치킨
1038kcal/42:96:54

In [96]:
#ppt 파일 열기
import win32com.client

file_name = f'메인 중식(파워트레인) {now_d}.pptx'

#powerpoint = win32com.client.Dispatch('PowerPoint.Application') #읽기모드 (이러면 수정은 되지만 현재 파일에 덮어쓰는게 안됨)
#powerpoint.Visible = True #PPT창 보이게 하기 

#파워포인트 프레젠테이션 불러오기
powerpoint = win32.gencache.EnsureDispatch("PowerPoint.Application") #읽기쓰기 모드로 열어야 현재 파일에 덮어쓰기 가능
#기존 파일 불러오기 예시
#presentation = powerpoint.Presentations.Open(str(match[0].resolve(), WithWindow=False))###파일 열때 파일명 앞에 절대경로 수정 필요 

#본관 조식 작업
presentation = powerpoint.Presentations.Open(folder_path+file_name, ReadOnly=False, WithWindow=True) #WithWindow=False로 하면 화면 안열고 진행

In [97]:
#a2 중식 1번째 슬라이드
slide = presentation.Slides(1)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#df.loc[21:27,col_name[today]] #a2 한식 중식
#화반(한식a)
#메인메뉴 데이터 수정
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu2_1
#반찬 수정
# shape_index = 11 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(a2_other_menu2)

#df.loc[43:49,col_name[today]] #a2 인터 중식
#메인메뉴 데이터 수정
shape_index = 13 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu3_1
#반찬 수정
# shape_index = 16 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(a2_other_menu3)

In [98]:
#a2 중식 2번째 슬라이드
slide = presentation.Slides(2)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

# df.loc[53:56,col_name[today]] #a2 런치팩
shape_index = 26 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu5_1

# df.loc[57:60,col_name[today]] #a2 샐러드팩 
shape_index = 27 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu6_1

# df.loc[64:66,col_name[today]] #a2관 모스버거팩 중식
shape_index = 29 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu8_1

# df.loc[61:63,col_name[today]] #C1관 고피자팩 중식
shape_index = 30 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu7_1

# df.loc[47:50,col_name[today]] #C1 자담치킨 중식
#메인메뉴 데이터 수정
shape_index = 31 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu9_1

In [99]:
#a2 중식 3번째 슬라이드
slide = presentation.Slides(3)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#df.loc[29:35,col_name[today]] #a2 고슬고슬 중식
shape_index = 14 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu1_1
#반찬 수정
# shape_index = 14 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# #메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
# shape.TextFrame.TextRange.Text = " / ".join(a2_other_menu1)

In [100]:
# 같은 파일에 덮어쓰기
presentation.Save()
# 닫기
presentation.Close()
#Quit는 Presentation(프레젠테이션) 객체가 아니라 Application(파워포인트 앱) 객체의 메서드라서 powerpoint를 닫아줘야함. 
#powerpoint.Quit()

In [101]:
#여기부터 코너 정보 넣기 작업 재시작 (지금셀 나중에 삭제)###############################################################
# #파워포인트 디렉토리
# root_path=os.getcwd()
# #print(root_path) #root 디렉토리
# folder_path = root_path+"\\25년"+"\\8월\\"+now_d+"\\" #폴더 디렉토리
# print(folder_path)

In [102]:
#중식 코너

#ppt 파일 열기
import win32com.client
file_name = f'코너 중식 {now_d} 원산지 입력.pptx'
#파워포인트 프레젠테이션 불러오기
powerpoint = win32.gencache.EnsureDispatch("PowerPoint.Application") #읽기쓰기 모드로 열어야 현재 파일에 덮어쓰기 가능
#기존 파일 불러오기 예시
#presentation = powerpoint.Presentations.Open(str(match[0].resolve(), WithWindow=False))###파일 열때 파일명 앞에 절대경로 수정 필요 
#본관 조식 작업
presentation = powerpoint.Presentations.Open(folder_path+file_name, ReadOnly=False, WithWindow=True) #WithWindow=False로 하면 화면 안열고 진행

In [103]:
#주간식단 파일 위치 (매주 수동변경)
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_본관.csv" #####################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8')#'cp949' 'euc-kr' 'cp949'

In [104]:
slide = presentation.Slides(4)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu1_1

#반찬 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[42:47,col_name[today]]]
last.append(main_menu7_1)
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", menu_data1) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [105]:
slide = presentation.Slides(5)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu2_1

#반찬 수정
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[49:54,col_name[today]]]
last.append(main_menu7_1)
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", menu_data2) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [106]:
slide = presentation.Slides(6)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu3_1

#반찬 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[56:61,col_name[today]] if type(x)==str]
last.append(main_menu7_1)
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", menu_data3) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [107]:
slide = presentation.Slides(7)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu4_1

#반찬 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[63:68,col_name[today]] if type(x)==str]
last.append(main_menu7_1)
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 6 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", menu_data4) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [108]:
slide = presentation.Slides(8)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = main_menu5_1

#반찬 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[70:75,col_name[today]] if type(x)==str]
last.append(main_menu7_1)
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 6 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", menu_data5) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [110]:
#저속노화
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_저속노화.csv" #################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8')#'cp949' 'euc-kr' 'cp949'
df.loc[3:8,col_name[today]] #저속노화 
df.loc[8:15,col_name[today]] #저당
df.loc[17:22,col_name[today]] #고혈압

17          ★토마토두부면파스타
18           ★닭가슴살스테이크
19                채소피클
20                ★탄산수
21                 NaN
22    794kcal/98:33:30
Name: Unnamed: 7, dtype: object

In [111]:
last = [x.replace("★","") for x in df.loc[3:7,col_name[today]] if type(x)==str]

parts = re.split(r"[/:]", menu_data0_1) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
#shape.TextFrame.TextRange.Text = parts
last.append(parts)
[x+"\n" for x in last]

['토마토두부면파스타\n',
 '닭가슴살스테이크\n',
 '채소피클\n',
 '탄산수\n',
 '794kcal (탄 98g/단 33g/지 30g)\n']

In [112]:
#저속노화
slide = presentation.Slides(10)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 3 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

#반찬 수정
last = [x.replace("★","") for x in df.loc[3:7,col_name[today]] if type(x)==str]

#kcal 탄단지
parts = re.split(r"[/:]", menu_data0_1) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
#shape.TextFrame.TextRange.Text = parts
last.append(parts)

shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

In [113]:
#저당
slide = presentation.Slides(11)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 5 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

#반찬 수정
last = [x.replace("★","") for x in df.loc[10:14,col_name[today]] if type(x)==str]

#kcal 탄단지
parts = re.split(r"[/:]", menu_data0_2) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
#shape.TextFrame.TextRange.Text = parts
last.append(parts)

shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#메인메뉴 데이터 수정
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

#반찬 수정
last = [x.replace("★","") for x in df.loc[17:21,col_name[today]] if type(x)==str]

#kcal 탄단지
parts = re.split(r"[/:]", menu_data0_3) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
#shape.TextFrame.TextRange.Text = parts
last.append(parts)

shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

In [114]:
#C지구
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_C.csv" #################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8') #'cp949' 'euc-kr' 'cp949'
df.loc[42:48,col_name[today]] #C 화반(한식a) 중식
df.loc[49:55,col_name[today]] #C 우글지글(한식b) 중식
df.loc[56:62,col_name[today]] #C 인터a(일미) 중식
df.loc[63:69,col_name[today]] #C 인터b(하오) 중식

63               ★경양식돈까스
64                  흑임자밥
65              ★파슬리크림수프
66                 ★채소쫄면
67                  오이피클
68                   깍두기
69    1065kcal/156:36:33
Name: Unnamed: 7, dtype: object

In [115]:
slide = presentation.Slides(13)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu1_1

#반찬 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[42:47,col_name[today]] if type(x)==str]
last.append(c_main_menu7_1)
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c_menu_data1) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [116]:
slide = presentation.Slides(14)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu2_1

#반찬 수정
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[49:54,col_name[today]]if type(x)==str]
last.append(c_main_menu7_1)
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c_menu_data2) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [117]:
slide = presentation.Slides(15)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu3_1

#반찬 수정
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[56:61,col_name[today]]if type(x)==str]
last.append(c_main_menu7_1)
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c_menu_data3) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [118]:
slide = presentation.Slides(16)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu4_1

#반찬 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[63:68,col_name[today]]if type(x)==str]
last.append(c_main_menu7_1)
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c_menu_data4) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [119]:
#더블치즈버거
slide = presentation.Slides(18)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 2 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu5_1

#반찬 수정
shape_index = 3 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[70:72,col_name[today]]if type(x)==str]
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c_menu_data5) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [120]:
#고피자
slide = presentation.Slides(19)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 2 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c_main_menu6_1

#반찬 수정
shape_index = 3 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[74:75,col_name[today]]if type(x)==str]
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c_menu_data6) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [121]:
#C1지구
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_C1.csv" #################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8') #'cp949' 'euc-kr' 'cp949'
df.loc[21:27,col_name[today]] #C1 화반(한식a) 중식
df.loc[28:34,col_name[today]] #C1 우글지글(한식b) 중식
df.loc[35:41,col_name[today]] #C1 인터 중식
df.loc[42:46,col_name[today]] #C1 더팬 중식

42              ★불고기반미버거
43                 ★크림수프
44            ★오이피클&할라피뇨
45                   깍두기
46    1033kcal/154:30:33
Name: Unnamed: 7, dtype: object

In [122]:
#한식a
slide = presentation.Slides(20)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu1_1

#반찬 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[21:26,col_name[today]]if type(x)==str]
last.append(c1_main_menu6_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c1_menu_data1) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [123]:
#한식b 우글지글
slide = presentation.Slides(21)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu2_1

#반찬 수정
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[28:33,col_name[today]]if type(x)==str]
last.append(c1_main_menu6_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c1_menu_data2) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [124]:
#인터
slide = presentation.Slides(22)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu3_1

#반찬 수정
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[35:40,col_name[today]]if type(x)==str]
last.append(c1_main_menu6_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c1_menu_data3) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [125]:
#더팬
slide = presentation.Slides(23)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu4_1

#반찬 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[42:45,col_name[today]]if type(x)==str]
last.append(c1_main_menu6_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c1_menu_data4) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [126]:
#텍스트 상자가 그룹화되면 텍스트 상자를 인식할 수 없음 주의

In [127]:
#그랩앤고
slide = presentation.Slides(24)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#런치팩
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu7_1

#kcal 탄단지
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c1_menu_data7) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

#샐러드팩
shape_index = 5 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu8_1

#kcal 탄단지
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c1_menu_data8) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

#모스버거팩
shape_index = 13 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#임시(삭제) 
# c1_main_menu10_1='미운영'#
# c1_menu_data10='미운영'#

shape.TextFrame.TextRange.Text = c1_main_menu10_1

#kcal 탄단지
shape_index = 14 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c1_menu_data10) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

#고피자팩
shape_index = 15 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = c1_main_menu9_1

#kcal 탄단지
shape_index = 16 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", c1_menu_data9) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

#자담치킨팩
# shape_index = 17 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)
# shape.TextFrame.TextRange.Text = c1_main_menu5_1

#kcal 탄단지
# shape_index = 18 # 수정할 텍스트박스의 Shape 번호
# shape = slide.Shapes(shape_index)

# parts = re.split(r"[/:]", c1_menu_data5) #/랑 :기준으로 split
# parts.insert(1, " (탄 ")
# parts.insert(3, "g/")
# parts.insert(4, "단 ")
# parts.insert(6, "g/")
# parts.insert(7, "지 ")
# parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [128]:
#디자인
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_A1.csv" #################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8') #'cp949' 'euc-kr' 'cp949'
df.loc[21:27,col_name[today]] #a1 고슬고슬 중식
df.loc[28:34,col_name[today]] #a1 한식 중식
df.loc[35:41,col_name[today]] #a1 인터 중식

35               ★경양식돈까스
36                  흑임자밥
37              ★파슬리크림수프
38                 ★채소쫄면
39                  오이피클
40                   깍두기
41    1065kcal/156:36:33
Name: Unnamed: 7, dtype: object

In [129]:
#고슬고슬
slide = presentation.Slides(25)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu1_1

#반찬 수정
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[21:26,col_name[today]]if type(x)==str]
last.append(a1_main_menu4_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a1_menu_data1) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

TypeError: expected string or bytes-like object

In [130]:
#한식
slide = presentation.Slides(26)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu2_1

#반찬 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[28:33,col_name[today]]if type(x)==str]
last.append(a1_main_menu4_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a1_menu_data2) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

TypeError: expected string or bytes-like object

In [131]:
#인터
slide = presentation.Slides(27)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu3_1

#반찬 수정
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[35:40,col_name[today]]if type(x)==str]
last.append(a1_main_menu4_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a1_menu_data3) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [132]:
#그랩앤고
slide = presentation.Slides(28)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#런치팩
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu5_1

#kcal 탄단지
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a1_menu_data5) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

#샐러드팩
shape_index = 5 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu6_1

#kcal 탄단지
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a1_menu_data6) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

#임시(삭제) 
# a1_main_menu8_1='미운영'#
# a1_menu_data8='미운영'#

#모스버거팩
shape_index = 13 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu8_1

#kcal 탄단지
shape_index = 14 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a1_menu_data8) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

#고피자팩
shape_index = 15 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu7_1

#kcal 탄단지
shape_index = 16 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a1_menu_data7) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

#자담치킨팩
shape_index = 17 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a1_main_menu9_1

#kcal 탄단지
shape_index = 18 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a1_menu_data9) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [133]:
#파워트레인
week_meal = "2025.12.29.현대차남양.통합주간식단표(게시)_A2.csv" #################파일 변경
df=pd.read_csv("./"+week_meal, encoding='utf-8') #'cp949' 'euc-kr' 'cp949'

In [134]:
#인터
slide = presentation.Slides(29)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu1_1

#반찬 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[29:34,col_name[today]]if type(x)==str]
#파워트레인 바나나는 계속해서 황도로 변경
a2_main_menu4_1.replace("바나나","황도")
last.append(a2_main_menu4_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 11 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a2_menu_data1) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [135]:
#인터
slide = presentation.Slides(30)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu2_1

#반찬 수정
shape_index = 8 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[36:41,col_name[today]]if type(x)==str]
#파워트레인 바나나는 계속해서 황도로 변경
a2_main_menu4_1.replace("바나나","황도")
last.append(a2_main_menu4_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a2_menu_data2) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [136]:
#인터
slide = presentation.Slides(31)
presentation = powerpoint.ActivePresentation
window = powerpoint.ActiveWindow

#메인메뉴 데이터 수정
shape_index = 9 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
shape.TextFrame.TextRange.Text = a2_main_menu3_1

#반찬 수정
shape_index = 10 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)
#메인메뉴 말고 반찬은 기존에 리스트로 되어있어서 . 기준으로 join해줌
last = [x.replace("★","") for x in df.loc[43:48,col_name[today]]if type(x)==str]
#파워트레인 바나나는 계속해서 황도로 변경
a2_main_menu4_1.replace("바나나","황도")
last.append(a2_main_menu4_1) 
shape.TextFrame.TextRange.Text = "".join([x+"\n" for x in last])

#kcal 탄단지
shape_index = 7 # 수정할 텍스트박스의 Shape 번호
shape = slide.Shapes(shape_index)

parts = re.split(r"[/:]", a2_menu_data3) #/랑 :기준으로 split
parts.insert(1, " (탄 ")
parts.insert(3, "g/")
parts.insert(4, "단 ")
parts.insert(6, "g/")
parts.insert(7, "지 ")
parts.insert(9, "g)")

parts="".join(parts)
shape.TextFrame.TextRange.Text = parts

In [137]:

# 같은 파일에 덮어쓰기
presentation.Save()
# 닫기
presentation.Close()
#Quit는 Presentation(프레젠테이션) 객체가 아니라 Application(파워포인트 앱) 객체의 메서드라서 powerpoint를 닫아줘야함. 
powerpoint.Quit()

In [138]:
# #작업을 위한 셀 #################################################################################################작업용
# #현재 선택된 개체 확인(확인용)
# # selection = window.Selection
# # selection

# slide = presentation.Slides(31)
# for i, shape in enumerate(slide.Shapes):
#     #모든 요소는 몇번째인지로 지정해서 수정이 들어감 ############################################################################
#     print(f"{i+1}번째 요소입니다.") #파이썬은 0부터 세고 ppt의 요소는 1부터 셈
#     #print("이름", shape.Name)
#     #print("타입", shape.Type)

#         # 텍스트 있는 경우만 내용 출력
#     if getattr(shape, "HasTextFrame", 0):
#         if shape.TextFrame.HasText:
#             text = shape.TextFrame.TextRange.Text
#             text = text.replace("\r", " ").replace("\n", " ")  # 줄바꿈 제거
#             print("텍스트 내용 :", text)
#         else:
#             print("텍스트 내용 : (비어 있음)")
#     else:
#         print("텍스트 내용 : (텍스트 프레임 없음)")
# #presentation.Slides(3).Select()

In [139]:
#선행 조건 왼쪽 원산지 부분에는 하단에 후식 한줄 추가 (단 파워트레인에서 황도가 들어갔을 땐 바나나로 변경 조건을 추가)
#마지막 줄이 겉절이나 김치라는 단어가 포함된다면 배추:국내산 / 고춧가루:중국산을 붙여서 하단에 추가


#선행 조건2 왼쪽 원산지 표기 부분이 완료되면 가장 하단에 있는 김치정보 줄을 붙여넣으려 했으나 실제 원산지 표기까지 들어가야 했기 때문에 수작업으로 진행
#kcal과 탄단지 변경 후 저장

#